In [1]:
import requests
import json
import html
import pandas as pd
import time
import re

C:\Users\Karina\miniconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

In [2]:
years = ['2021', '2022', '2023', '2024']
races = ['TOR330', 'TOR450', 'TOR130']

## Loading Data

In [8]:

TORX_df = {}
aid_stations_TORX_df = {}

for race in races:
    for year in years:
        df = pd.read_excel(f'{race} Data/100x100trail/{race}_{year}.xlsx')
        print(f'{race}_{year} {df.shape}')
        try:
            for column in df.columns:
                df[column] = df[column].str.strip().str.title()
                df[column] = df[column].str.replace(',', '')
                df[column] = df[column].str.replace('\'', ' ')
                df[column] = df[column].str.replace('-', ' ')
                df[column] = df[column].str.replace(r"\s+", " ")
                df[column] = df[column].apply(normalize_name)
                
                df[column] = re.sub(r"\s+", " ", df[column]).strip().title()
                
                print(df.shape)
        except:
            pass

        # Store the DataFrame in the dictionary with a key like 'TOR330_2021'
        TORX_df[f'{race}_{year}'] = df
    print('*'*50)
        
#         print(f"Data read from f'{race}_{year}.xlsx'")

TOR330_2021 (712, 8)
TOR330_2022 (960, 8)
TOR330_2023 (1206, 8)
TOR330_2024 (1096, 8)
**************************************************
TOR450_2021 (56, 8)
TOR450_2022 (149, 8)
TOR450_2023 (187, 8)
TOR450_2024 (185, 8)
**************************************************
TOR130_2021 (264, 8)
TOR130_2022 (388, 8)
TOR130_2023 (505, 8)
TOR130_2024 (393, 8)
**************************************************

In [4]:
TORX_df_excel = pd.concat(TORX_df)
TORX_df_excel.to_excel(f'Database Data/TORX_df_100x100_trail.xlsx' , index = False)

In [5]:
TORX_df_excel

                  Bib              Name  \
TOR330_2021 0       1      Colle Franco
            1     417      Jonas  Russi
            2       2    Restorp Petter
            3      10     Picinali Luca
            4       5    Corsini Simone
...               ...               ...
TOR130_2024 388  2459   Petrella Sandro
            389  2364      Puccini Dino
            390  2225    Kovsca Stefano
            391  2495      Lee Heewoong
            392  2353  Sutherland Jason

                                                              Team Sex  \
TOR330_2021 0                                         HOKA  KARPOS   M
            1    HOKA ONE ONE / russimassagepraxis / LEKI / GLO...   M
            2                                          La Sportiva   M
            3                                           GS Orezzo    M
            4                          Atletica Mds Panaria Group    M
...                                                            ...  ..
TOR130_2024 388                                                NaN   M
            389                                TEAM MUD & SNOW ASD   M
            390                                                NaN   M
            391                                                NaN   M
            392                                                NaN   M

                Nationality    Race  Year  Status
TOR330_2021 0            IT  TOR330  2021    True
            1            CH  TOR330  2021    True
            2            FR  TOR330  2021    True
            3            IT  TOR330  2021    True
            4            IT  TOR330  2021    True
...                     ...     ...   ...     ...
TOR130_2024 388          IT  TOR130  2024   False
            389          IT  TOR130  2024   False
            390          IT  TOR130  2024   False
            391          KR  TOR130  2024   False
            392          US  TOR130  2024   False

[6101 rows x 8 columns]

### Exploring Data

In [6]:
# print(tor_des_glacier_df[f'tor_des_glacier_2024'])
df = TORX_df[f'TOR330_2024'][TORX_df[f'TOR330_2024']['Name'] == 'D Haene Francois']

df

,Bib,Name,Team,Sex,Nationality,Race,Year,Status
0,10,D Haene Francois,SALOMON INTERNATIONNAL,M,FR,TOR330,2024,True