In [1]:
import requests
import json
import html
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import unicodedata
import re

C:\Users\Karina\miniconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

In [2]:
# Function to remove special characters
def normalize_name(name):
    # Normalize to remove accents and special characters
    name = unicodedata.normalize('NFD', name)
    # Encode to ASCII and ignore errors, then decode back to string
    name = name.encode('ascii', 'ignore').decode('utf-8')
    return name

In [3]:

# # URL of the JSON file
# url = "https://itra.run/Races/RaceResults/TOR330.Tor.des.G%C3%A9ants%C2%AE/2023/80226"

# # Send a GET request to fetch the JSON data
# response = requests.get(url)
# response

In [4]:
years = [ '2024', '2023', 
         '2022', 
         '2022_HOTEL_ITALIA',  # bad weather at the end 
         '2022_RIFUGIO_FRASSATI',
         '2022_BOSSES',
         '2021', 
         '2019',
#          '2020', # cancelled due to covid
         '2018', '2017', '2016', 
         #'2015', # having issues with 2015
         '2014', '2013', '2012', '2011', '2010']

races = ['TOR130', 'TOR330', 'TOR450'
        ]

#### Loading ITRA

In [5]:

TORX_itra_df = {}
# races = ['TOR450']

for race in races:
    for year in years:
        try:

            file = f'{race} Data/3. ITRA/TXT/{race}_{year}.txt'
            df = pd.read_csv(file, delimiter='\t', 
                         dtype={'Time': 'string'})    

            # renaming columns so it is easier later to compare
            df = df.rename(columns={"Runner": "Name",
                                    "Gender": "Sex",
                                    "Nationality": "ITRA_Nationality",
                                   })

            # change the name to a title case
            df['Name'] = df['Name'].str.title()
            df['Name'] = df['Name'].apply(normalize_name)

            # Convert 'Time' to timedelta format
            df['Performance'] = pd.to_timedelta(df['Time'], errors='coerce')
            # Calculate total seconds and create 'Performance_Seconds' column
            df['Performance_Seconds'] = df['Performance'].dt.total_seconds()

            if year == '2022_HOTEL_ITALIA':
            # Create the 'Status' column
                df['Status'] =  'Finished at Hotel Italia'
                df['Year'] = '2022'    
            elif year == '2022_RIFUGIO_FRASSATI':
                df['Status'] = 'Finished at Rifugio Frassati'
                df['Year'] = '2022'
            elif year == '2022_BOSSES':
                df['Status'] =  'Finished at Bosses'
                df['Year'] = '2022'
            else:
                df['Status'] = np.where(df['Performance'].isna(), 'DNF', 'Finished')
                df['Year'] = f'{year}'

            df['Race'] = f'{race}'

    #             # Drop the intermediate columns if they're no longer needed
            df = df.drop(columns=['Time', '#'])

            df['Name'] = df['Name'].str.strip()
            df['Name'] = df['Name'].str.replace(',', '')
            df['Name'] = df['Name'].str.replace('\'', '')
            df['Name'] = df['Name'].str.replace('-', '')
            df['Name'] = df['Name'].str.replace(r"\s+", " ")

    #             print(race, year, '\n', df.head())

            # Store the DataFrame in the dictionary with a key like 'TOR330_2021'
            TORX_itra_df[f'{race}_{year}'] = df
            print('* ',f'{race}_{year} {df.shape}', '\n')
        except:
            
            if file == 'TOR330 Data/3. ITRA/TXT/TOR330_2022_HOTEL_ITALIA.txt':
                pass
            elif file == 'TOR450 Data/3. ITRA/TXT/TOR450_2022_RIFUGIO_FRASSATI.txt':
                pass
            elif file == 'TOR450 Data/3. ITRA/TXT/TOR330_2022_BOSSES.txt':
                pass
            
            else:
                print(f'issues with {race}_{year}')
                print(f'{file}')
                print('\n')

issues with TOR130_2024
TOR130 Data/3. ITRA/TXT/TOR130_2024.txt


issues with TOR130_2023
TOR130 Data/3. ITRA/TXT/TOR130_2023.txt


issues with TOR130_2022
TOR130 Data/3. ITRA/TXT/TOR130_2022.txt


issues with TOR130_2022_HOTEL_ITALIA
TOR130 Data/3. ITRA/TXT/TOR130_2022_HOTEL_ITALIA.txt


issues with TOR130_2022_RIFUGIO_FRASSATI
TOR130 Data/3. ITRA/TXT/TOR130_2022_RIFUGIO_FRASSATI.txt


issues with TOR130_2022_BOSSES
TOR130 Data/3. ITRA/TXT/TOR130_2022_BOSSES.txt


issues with TOR130_2021
TOR130 Data/3. ITRA/TXT/TOR130_2021.txt


issues with TOR130_2019
TOR130 Data/3. ITRA/TXT/TOR130_2019.txt


issues with TOR130_2018
TOR130 Data/3. ITRA/TXT/TOR130_2018.txt


issues with TOR130_2017
TOR130 Data/3. ITRA/TXT/TOR130_2017.txt


issues with TOR130_2016
TOR130 Data/3. ITRA/TXT/TOR130_2016.txt


issues with TOR130_2014
TOR130 Data/3. ITRA/TXT/TOR130_2014.txt


issues with TOR130_2013
TOR130 Data/3. ITRA/TXT/TOR130_2013.txt


issues with TOR130_2012
TOR130 Data/3. ITRA/TXT/TOR130_2012.txt


issues with TOR130_2011
TOR130 Data/3. ITRA/TXT/TOR130_2011.txt


issues with TOR130_2010
TOR130 Data/3. ITRA/TXT/TOR130_2010.txt


*  TOR330_2024 (1085, 9)

*  TOR330_2023 (1093, 9)

*  TOR330_2022 (408, 9)

*  TOR330_2022_RIFUGIO_FRASSATI (101, 9)

*  TOR330_2022_BOSSES (81, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR330_2021 (712, 9)

*  TOR330_2019 (941, 9)

*  TOR330_2018 (879, 9)

*  TOR330_2017 (461, 9)

*  TOR330_2016 (445, 9)

*  TOR330_2014 (443, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR330_2013 (383, 9)

*  TOR330_2012 (391, 9)

*  TOR330_2011 (300, 9)

*  TOR330_2010 (179, 9)

*  TOR450_2024 (168, 9)

*  TOR450_2023 (173, 9)

*  TOR450_2022 (46, 9)

C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

*  TOR450_2022_HOTEL_ITALIA (11, 9)

issues with TOR450_2022_BOSSES
TOR450 Data/3. ITRA/TXT/TOR450_2022_BOSSES.txt


*  TOR450_2021 (56, 9)

*  TOR450_2019 (100, 9)

issues with TOR450_2018
TOR450 Data/3. ITRA/TXT/TOR450_2018.txt


issues with TOR450_2017
TOR450 Data/3. ITRA/TXT/TOR450_2017.txt


issues with TOR450_2016
TOR450 Data/3. ITRA/TXT/TOR450_2016.txt


issues with TOR450_2014
TOR450 Data/3. ITRA/TXT/TOR450_2014.txt


issues with TOR450_2013
TOR450 Data/3. ITRA/TXT/TOR450_2013.txt


issues with TOR450_2012
TOR450 Data/3. ITRA/TXT/TOR450_2012.txt


issues with TOR450_2011
TOR450 Data/3. ITRA/TXT/TOR450_2011.txt


issues with TOR450_2010
TOR450 Data/3. ITRA/TXT/TOR450_2010.txt

C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")
C:\Users\Karina\AppData\Local\Temp\ipykernel_8604\2679965923.py:50: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Name'] = df['Name'].str.replace(r"\s+", " ")

In [6]:
for race in races:
    for year in years:
        try:
            tor_year = TORX_itra_df[f'{race}_{year}']
            # Count the occurrences of each status
            status_counts = tor_year['Status'].value_counts()
            print(race, year, '\n', status_counts, '\n', '*'*40)
        except:
            pass

TOR330 2024
 DNF         552
Finished    533
Name: Status, dtype: int64
 ****************************************
TOR330 2023
 Finished    621
DNF         472
Name: Status, dtype: int64
 ****************************************
TOR330 2022
 Finished    408
Name: Status, dtype: int64
 ****************************************
TOR330 2022_RIFUGIO_FRASSATI
 Finished at Rifugio Frassati    101
Name: Status, dtype: int64
 ****************************************
TOR330 2022_BOSSES
 Finished at Bosses    81
Name: Status, dtype: int64
 ****************************************
TOR330 2021
 Finished    431
DNF         281
Name: Status, dtype: int64
 ****************************************
TOR330 2019
 Finished    563
DNF         378
Name: Status, dtype: int64
 ****************************************
TOR330 2018
 Finished    534
DNF         345
Name: Status, dtype: int64
 ****************************************
TOR330 2017
 Finished    461
Name: Status, dtype: int64
 ****************************************
TOR330 2016
 Finished    445
Name: Status, dtype: int64
 ****************************************
TOR330 2014
 Finished    443
Name: Status, dtype: int64
 ****************************************
TOR330 2013
 Finished    383
Name: Status, dtype: int64
 ****************************************
TOR330 2012
 Finished    391
Name: Status, dtype: int64
 ****************************************
TOR330 2011
 Finished    300
Name: Status, dtype: int64
 ****************************************
TOR330 2010
 Finished    179
Name: Status, dtype: int64
 ****************************************
TOR450 2024
 DNF         100
Finished     68
Name: Status, dtype: int64
 ****************************************
TOR450 2023
 DNF         88
Finished    85
Name: Status, dtype: int64
 ****************************************
TOR450 2022
 Finished    46
Name: Status, dtype: int64
 ****************************************
TOR450 2022_HOTEL_ITALIA
 Finished at Hotel Italia    11
Name: Status, dtype: int64
 ****************************************
TOR450 2021
 Finished    31
DNF         25
Name: Status, dtype: int64
 ****************************************
TOR450 2019
 DNF         60
Finished    40
Name: Status, dtype: int64
 ****************************************

In [7]:
TORX_itra_df

{'TOR330_2024':                     Name Age Sex ITRA_Nationality     Performance  \
 0       D Haene Francois  39   M              FRA 2 days 21:08:32
 1      Marmissolle Benat  43   M              FRA 3 days 01:10:18
 2         Perrier Martin  34   M              FRA 3 days 03:35:59
 3          Macchi Andrea  38   M              ITA 3 days 04:43:09
 4            Hall Damian  49   M              GBR 3 days 04:49:20
 ...                  ...  ..  ..              ...             ...
 1080        Zimei Andrea  44   M              ITA             NaT
 1081  Zinfolino Federica  47   F              ITA             NaT
 1082       Zoratti Mauro  36   M              ITA             NaT
 1083       Zou Hongjiang  43   M              CHN             NaT
 1084                      56   M              JPN             NaT

       Performance_Seconds    Status  Year    Race
 0                248912.0  Finished  2024  TOR330
 1                263418.0  Finished  2024  TOR330
 2                272159.0  Finished  2024  TOR330
 3                276189.0  Finished  2024  TOR330
 4                276560.0  Finished  2024  TOR330
 ...                   ...       ...   ...     ...
 1080                  NaN       DNF  2024  TOR330
 1081                  NaN       DNF  2024  TOR330
 1082                  NaN       DNF  2024  TOR330
 1083                  NaN       DNF  2024  TOR330
 1084                  NaN       DNF  2024  TOR330

 [1085 rows x 9 columns],
 'TOR330_2023':                   Name Age Sex ITRA_Nationality     Performance  \
 0         Colle Franco  45   M              ITA 2 days 18:39:16
 1       Olivier Romain  38   M              FRA 2 days 21:49:38
 2       Reynolds Galen  39   M              CAN 2 days 23:22:30
 3          Hall Damian  48   M              GBR 3 days 00:04:07
 4     Galeati Gianluca  40   M              ITA 3 days 00:16:06
 ...                ...  ..  ..              ...             ...
 1088    Zenato Michele  58   M              ITA             NaT
 1089         Zhao Long  44   M              CHN             NaT
 1090    Zheng Xiao Hui  52   M              CAN             NaT
 1091     Ziemba Damian  45   M              POL             NaT
 1092     Zou Hongjiang  42   M              CHN             NaT

       Performance_Seconds    Status  Year    Race
 0                239956.0  Finished  2023  TOR330
 1                251378.0  Finished  2023  TOR330
 2                256950.0  Finished  2023  TOR330
 3                259447.0  Finished  2023  TOR330
 4                260166.0  Finished  2023  TOR330
 ...                   ...       ...   ...     ...
 1088                  NaN       DNF  2023  TOR330
 1089                  NaN       DNF  2023  TOR330
 1090                  NaN       DNF  2023  TOR330
 1091                  NaN       DNF  2023  TOR330
 1092                  NaN       DNF  2023  TOR330

 [1093 rows x 9 columns],
 'TOR330_2022':                          Name Age Sex ITRA_Nationality     Performance  \
 0                 Russi Jonas  37   M              SUI 2 days 22:31:36
 1              Corsini Simone  30   M              ITA 3 days 03:27:33
 2               Macchi Andrea  36   M              ITA 3 days 04:43:50
 3             Mattiato Andrea  44   M              ITA 3 days 06:22:28
 4              Sabrina Verjee  41   F              GBR 3 days 08:19:38
 ..                        ...  ..  ..              ...             ...
 403            Bentham Darren  54   M              GBR 5 days 22:58:14
 404            Longhi Giorgio  53   M              ITA 5 days 22:58:18
 405             Costa Alberto  38   M              ITA 6 days 00:21:06
 406  Colletto Davide Colletto  36   M              ITA 6 days 00:21:18
 407  Amar Delapierre Jocelyne  59   F              FRA 6 days 00:33:43

      Performance_Seconds    Status  Year    Race
 0               253896.0  Finished  2022  TOR330
 1               271653.0  Finished  2022  TOR330
 2               276230.0  Finished  2022  TOR330
 3               282148.0  Finished  2022  TOR330
 4               289178.0  Finished  2022  TOR330
 ..                   ...       ...   ...     ...
 403             514694.0  Finished  2022  TOR330
 404             514698.0  Finished  2022  TOR330
 405             519666.0  Finished  2022  TOR330
 406             519678.0  Finished  2022  TOR330
 407             520423.0  Finished  2022  TOR330

 [408 rows x 9 columns],
 'TOR330_2022_RIFUGIO_FRASSATI':                             Name Age Sex ITRA_Nationality     Performance  \
 0                Roveri Giovanni  53   M              ITA 5 days 07:59:29
 1                    Rossi Carlo  50   M              ITA 5 days 08:17:39
 2              Severino Giovanni  47   M              ITA 5 days 10:01:00
 3             Lloyd Hughes Torin  21   M              GBR 5 days 11:44:40
 4                 Borne Aurelien  38   M              FRA 5 days 12:04:17
 ..                           ...  ..  ..              ...             ...
 96   Rioboo Escalante Jon Mirena  56   M              ESP 5 days 20:26:55
 97          Riera Campillo Pablo  49   M              ESP 5 days 20:26:59
 98                  Werneck Fred  43   M              BRA 5 days 20:27:50
 99                  Lelu Olivier  52   M              FRA 5 days 20:49:44
 100                    Huang Ken  51   F              USA 5 days 22:26:49

      Performance_Seconds                        Status  Year    Race
 0               460769.0  Finished at Rifugio Frassati  2022  TOR330
 1               461859.0  Finished at Rifugio Frassati  2022  TOR330
 2               468060.0  Finished at Rifugio Frassati  2022  TOR330
 3               474280.0  Finished at Rifugio Frassati  2022  TOR330
 4               475457.0  Finished at Rifugio Frassati  2022  TOR330
 ..                   ...                           ...   ...     ...
 96              505615.0  Finished at Rifugio Frassati  2022  TOR330
 97              505619.0  Finished at Rifugio Frassati  2022  TOR330
 98              505670.0  Finished at Rifugio Frassati  2022  TOR330
 99              506984.0  Finished at Rifugio Frassati  2022  TOR330
 100             512809.0  Finished at Rifugio Frassati  2022  TOR330

 [101 rows x 9 columns],
 'TOR330_2022_BOSSES':                  Name Age Sex ITRA_Nationality     Performance  \
 0     Broggi Vittorio  61   M              ITA 5 days 10:42:26
 1    Balossi Giordano  53   M              ITA 5 days 11:17:16
 2     Renard Delphine  40   F              BEL 5 days 11:51:02
 3   Tsujimoto Arihito  52   M              JPN 5 days 12:42:55
 4      Butler Rebecca  51   F              AUS 5 days 12:46:27
 ..                ...  ..  ..              ...             ...
 76   Bertrand Ludovic  56   M              FRA 5 days 20:17:15
 77   Diemoz Ferruccio  52   M              ITA 5 days 20:17:24
 78         Kurita Eri  50   F              JPN 5 days 20:18:03
 79       Isidori Luca  56   M              ITA 5 days 20:18:22
 80      Ghedi Osvaldo  55   M              ITA 5 days 20:18:40

     Performance_Seconds              Status  Year    Race
 0              470546.0  Finished at Bosses  2022  TOR330
 1              472636.0  Finished at Bosses  2022  TOR330
 2              474662.0  Finished at Bosses  2022  TOR330
 3              477775.0  Finished at Bosses  2022  TOR330
 4              477987.0  Finished at Bosses  2022  TOR330
 ..                  ...                 ...   ...     ...
 76             505035.0  Finished at Bosses  2022  TOR330
 77             505044.0  Finished at Bosses  2022  TOR330
 78             505083.0  Finished at Bosses  2022  TOR330
 79             505102.0  Finished at Bosses  2022  TOR330
 80             505120.0  Finished at Bosses  2022  TOR330

 [81 rows x 9 columns],
 'TOR330_2021':                                Name Age Sex ITRA_Nationality     Performance  \
 0                      Colle Franco  43   M              ITA 2 days 18:43:57
 1                       Jonas Russi  36   M              SUI 2 days 21:03:00
 2                    Restorp Petter  44   M              SWE 3 days 04:36:00
 3                     Picinali Luca  48   M              ITA 3 days 09:31:00
 4                    Corsini Simone  29   M              ITA 3 days 10:45:52
 ..                              ...  ..  ..              ...             ...
 707  Zanderighi Luca Giovanni Maria  63   M              ITA             NaT
 708                 Zanon Francesco  26   M              ITA             NaT
 709               Zapata Munoz Juan  48   M              ESP             NaT
 710   Zavelani Rossi Maria Beatrice  56   F              ITA             NaT
 711                  Zenato Michele  56   M              ITA             NaT

      Performance_Seconds    Status  Year    Race
 0               240237.0  Finished  2021  TOR330
 1               248580.0  Finished  2021  TOR330
 2               275760.0  Finished  2021  TOR330
 3               293460.0  Finished  2021  TOR330
 4               297952.0  Finished  2021  TOR330
 ..                   ...       ...   ...     ...
 707                  NaN       DNF  2021  TOR330
 708                  NaN       DNF  2021  TOR330
 709                  NaN       DNF  2021  TOR330
 710                  NaN       DNF  2021  TOR330
 711                  NaN       DNF  2021  TOR330

 [712 rows x 9 columns],
 'TOR330_2019':                    Name Age Sex ITRA_Nationality     Performance  \
 0    Bosatelli Oliviero  50   M              ITA 3 days 00:37:13
 1        Reynolds Galen  35   M              CAN 3 days 05:06:12
 2     Lantermino Danilo  38   M              ITA 3 days 07:09:46
 3           Erwee Tiaan  32   M              RSA 3 days 08:18:24
 4            Lukas Jens  53   M              GER 3 days 13:04:04
 ..                  ...  ..  ..              ...             ...
 936         Zhang Yuren  48   M              CHN             NaT
 937        Zhao Yingkai  39   M              CHN             NaT
 938        Zheng Junyue  33   F              CHN             NaT
 939   Zimmermann Denise  44   F              SUI             NaT
 940       Zoppi Filippo  48   M              ITA             NaT

      Performance_Seconds    Status  Year    Race
 0               261433.0  Finished  2019  TOR330
 1               277572.0  Finished  2019  TOR330
 2               284986.0  Finished  2019  TOR330
 3               289104.0  Finished  2019  TOR330
 4               306244.0  Finished  2019  TOR330
 ..                   ...       ...   ...     ...
 936                  NaN       DNF  2019  TOR330
 937                  NaN       DNF  2019  TOR330
 938                  NaN       DNF  2019  TOR330
 939                  NaN       DNF  2019  TOR330
 940                  NaN       DNF  2019  TOR330

 [941 rows x 9 columns],
 'TOR330_2018':                    Name Age Sex ITRA_Nationality     Performance  \
 0          Colle Franco  40   M              ITA 3 days 02:03:00
 1        Reynolds Galen  34   M              CAN 3 days 02:40:36
 2          Kienzl Peter  43   M              ITA 3 days 05:31:11
 3    Bosatelli Oliviero  49   M              ITA 3 days 08:49:26
 4         Toriumi Kouta  33   M              JPN 3 days 08:58:35
 ..                  ...  ..  ..              ...             ...
 874           Zdon Bill  33   M              USA             NaT
 875      Zennaro Davide  57   M              ITA             NaT
 876        Zimei Andrea  38   M              ITA             NaT
 877   Zimmermann Denise  43   F              SUI             NaT
 878        Zugna Davide  42   M              ITA             NaT

      Performance_Seconds    Status  Year    Race
 0               266580.0  Finished  2018  TOR330
 1               268836.0  Finished  2018  TOR330
 2               279071.0  Finished  2018  TOR330
 3               290966.0  Finished  2018  TOR330
 4               291515.0  Finished  2018  TOR330
 ..                   ...       ...   ...     ...
 874                  NaN       DNF  2018  TOR330
 875                  NaN       DNF  2018  TOR330
 876                  NaN       DNF  2018  TOR330
 877                  NaN       DNF  2018  TOR330
 878                  NaN       DNF  2018  TOR330

 [879 rows x 9 columns],
 'TOR330_2017':                       Name Age Sex ITRA_Nationality     Performance  \
 0    Dominguez Ledo Javier  43   M              ESP 2 days 19:52:15
 1       Bosatelli Oliviero  48   M              ITA 2 days 21:16:19
 2            Macchi Andrea  31   M              ITA 3 days 02:51:14
 3                Sa Carlos  44   M              POR 3 days 08:20:34
 4            Aleson Imanol  45   M              ESP 3 days 09:17:37
 ..                     ...  ..  ..              ...             ...
 456             Juang Than  39   M              THA 6 days 05:45:13
 457   Rumyantseva Evgeniya  33   F              RUS 6 days 05:45:50
 458       Yoshimoto Makoto  53   M              JPN 6 days 05:51:42
 459           Shi Jianxiao  33   M              CHN 6 days 06:39:42
 460           Ng Seow Kong  56   M              MAS 6 days 08:40:29

      Performance_Seconds    Status  Year    Race
 0               244335.0  Finished  2017  TOR330
 1               249379.0  Finished  2017  TOR330
 2               269474.0  Finished  2017  TOR330
 3               289234.0  Finished  2017  TOR330
 4               292657.0  Finished  2017  TOR330
 ..                   ...       ...   ...     ...
 456             539113.0  Finished  2017  TOR330
 457             539150.0  Finished  2017  TOR330
 458             539502.0  Finished  2017  TOR330
 459             542382.0  Finished  2017  TOR330
 460             549629.0  Finished  2017  TOR330

 [461 rows x 9 columns],
 'TOR330_2016':                      Name Age Sex ITRA_Nationality     Performance  \
 0      Bosatelli Oliviero  47   M              ITA 3 days 03:10:22
 1       Perez Lopez Oscar  43   M              ESP 3 days 09:14:50
 2       Criado Toca Pablo  40   M              ESP 3 days 11:40:10
 3        Ressencourt Eric  41   M              FRA 3 days 12:06:32
 4              Lukas Jens  50   M              GER 3 days 13:47:50
 ..                    ...  ..  ..              ...             ...
 440        Leveque Claude  37   M              ITA 6 days 05:40:09
 441      Yoshimoto Makoto  52   M              JPN 6 days 05:41:31
 442        Bourva Laurent  56   M              FRA 6 days 05:44:03
 443        Manoni Giorgio  45   M              ITA 6 days 05:55:38
 444  Bustamante Velez Ana  48   F              ESP 6 days 05:55:39

      Performance_Seconds    Status  Year    Race
 0               270622.0  Finished  2016  TOR330
 1               292490.0  Finished  2016  TOR330
 2               301210.0  Finished  2016  TOR330
 3               302792.0  Finished  2016  TOR330
 4               308870.0  Finished  2016  TOR330
 ..                   ...       ...   ...     ...
 440             538809.0  Finished  2016  TOR330
 441             538891.0  Finished  2016  TOR330
 442             539043.0  Finished  2016  TOR330
 443             539738.0  Finished  2016  TOR330
 444             539739.0  Finished  2016  TOR330

 [445 rows x 9 columns],
 'TOR330_2014':                    Name Age Sex ITRA_Nationality     Performance  \
 0          Colle Franco  36   M              ITA 2 days 23:49:10
 1           Hollon Nick  25   M              USA 3 days 04:29:38
 2       Guillon Antoine  44   M              FRA 3 days 07:02:29
 3    Le Saux Christophe  42   M              FRA 3 days 07:02:29
 4          Ono Masahiro  33   M              JPN 3 days 11:04:15
 ..                  ...  ..  ..              ...             ...
 438      Hashimoto Miki  41   F              JPN 6 days 05:33:07
 439      Tsang Hing Kin  46   M              HKG 6 days 05:33:45
 440   Matsunuma Yoshiko  53   F              JPN 6 days 05:39:45
 441    Chienno Philippe  43   M              FRA 6 days 05:41:57
 442         Desez Alain  54   M              FRA 6 days 05:42:41

      Performance_Seconds    Status  Year    Race
 0               258550.0  Finished  2014  TOR330
 1               275378.0  Finished  2014  TOR330
 2               284549.0  Finished  2014  TOR330
 3               284549.0  Finished  2014  TOR330
 4               299055.0  Finished  2014  TOR330
 ..                   ...       ...   ...     ...
 438             538387.0  Finished  2014  TOR330
 439             538425.0  Finished  2014  TOR330
 440             538785.0  Finished  2014  TOR330
 441             538917.0  Finished  2014  TOR330
 442             538961.0  Finished  2014  TOR330

 [443 rows x 9 columns],
 'TOR330_2013':                   Name Age Sex ITRA_Nationality     Performance  \
 0         Karrera Iker  39   M              ESP 2 days 22:04:15
 1    Perez Lopez Oscar  40   M              ESP 2 days 22:29:41
 2         Colle Franco  35   M              ITA 3 days 00:05:23
 3        Trivel Lionel  43   M              FRA 3 days 05:02:53
 4       Bohard Patrick  49   M              FRA 3 days 06:47:46
 ..                 ...  ..  ..              ...             ...
 378  Matsunuma Yoshiko  52   F              JPN 6 days 05:07:18
 379   Robini Alexandre  62   M              FRA 6 days 05:13:40
 380  Melacarne Michele  58   M              ITA 6 days 05:30:37
 381     Zenato Michele  48   M              ITA 6 days 06:42:25
 382      Torres Claude  57   F              FRA 6 days 06:42:54

      Performance_Seconds    Status  Year    Race
 0               252255.0  Finished  2013  TOR330
 1               253781.0  Finished  2013  TOR330
 2               259523.0  Finished  2013  TOR330
 3               277373.0  Finished  2013  TOR330
 4               283666.0  Finished  2013  TOR330
 ..                   ...       ...   ...     ...
 378             536838.0  Finished  2013  TOR330
 379             537220.0  Finished  2013  TOR330
 380             538237.0  Finished  2013  TOR330
 381             542545.0  Finished  2013  TOR330
 382             542574.0  Finished  2013  TOR330

 [383 rows x 9 columns],
 'TOR330_2012':                    Name Age Sex ITRA_Nationality     Performance  \
 0     Perez Lopez Oscar  39   M              ESP 3 days 03:56:31
 1       Millet Gregoire  50   M              FRA 3 days 06:50:03
 2    Le Saux Christophe  40   M              FRA 3 days 08:14:14
 3     Criado Toca Pablo  36   M              ESP 3 days 11:37:29
 4          Colle Franco  34   M              ITA 3 days 12:15:59
 ..                  ...  ..  ..              ...             ...
 386      Nario Toshiaki  53   M              JPN 5 days 22:49:55
 387   Savoye Christophe   -   M              ITA 5 days 22:50:40
 388     Favre Francesco  38   M              ITA 5 days 22:51:06
 389      Sarvadon Piero  46   M              ITA 5 days 22:57:05
 390      Sarvadon Paolo  50   M              ITA 5 days 22:58:24

      Performance_Seconds    Status  Year    Race
 0               273391.0  Finished  2012  TOR330
 1               283803.0  Finished  2012  TOR330
 2               288854.0  Finished  2012  TOR330
 3               301049.0  Finished  2012  TOR330
 4               303359.0  Finished  2012  TOR330
 ..                   ...       ...   ...     ...
 386             514195.0  Finished  2012  TOR330
 387             514240.0  Finished  2012  TOR330
 388             514266.0  Finished  2012  TOR330
 389             514625.0  Finished  2012  TOR330
 390             514704.0  Finished  2012  TOR330

 [391 rows x 9 columns],
 'TOR330_2011':                         Name Age Sex ITRA_Nationality     Performance  \
 0        Gabioud Jules Henri  24   M              SUI 3 days 07:58:26
 1         Le Saux Christophe  39   M              FRA 3 days 12:09:46
 2          Criado Toca Pablo  35   M              ESP 3 days 17:43:07
 3            Gross Annemarie  42   F              ITA 3 days 19:28:21
 4                Arveux Eric  48   M              FRA 3 days 20:55:46
 ..                       ...  ..  ..              ...             ...

In [8]:
# Append using pd.concat
TORX_itra_df = pd.concat(TORX_itra_df)
TORX_itra_df = TORX_itra_df.reset_index(drop = True)
TORX_itra_df.isna().sum()

Name                      0
Age                       0
Sex                      13
ITRA_Nationality          0
Performance            2301
Performance_Seconds    2301
Status                    0
Year                      0
Race                      0
dtype: int64

In [9]:
years_list = TORX_itra_df['Year'].unique()
race_list = TORX_itra_df['Race'].unique()

for race in races:
    for year in years_list:
        year_df = TORX_itra_df[(TORX_itra_df['Year'] == year) &
                              (TORX_itra_df['Race'] == race)]
        status_df = year_df['Status'].value_counts()
        
        if race == 'TOR450' and year in [ 
            #'2020', # cancelled due to covid
         '2018', '2017', '2016', 
         '2015', 
         '2014', '2013', '2012', '2011', '2010']:
            pass
        else:
            print(race, year,'\n',status_df, '\n', '*'*40)

TOR130 2024
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2023
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2022
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2021
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2019
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2018
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2017
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2016
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2014
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2013
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2012
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2011
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR130 2010
 Series([], Name: Status, dtype: int64)
 ****************************************
TOR330 2024
 DNF         552
Finished    533
Name: Status, dtype: int64
 ****************************************
TOR330 2023
 Finished    621
DNF         472
Name: Status, dtype: int64
 ****************************************
TOR330 2022
 Finished                        408
Finished at Rifugio Frassati    101
Finished at Bosses               81
Name: Status, dtype: int64
 ****************************************
TOR330 2021
 Finished    431
DNF         281
Name: Status, dtype: int64
 ****************************************
TOR330 2019
 Finished    563
DNF         378
Name: Status, dtype: int64
 ****************************************
TOR330 2018
 Finished    534
DNF         345
Name: Status, dtype: int64
 ****************************************
TOR330 2017
 Finished    461
Name: Status, dtype: int64
 ****************************************
TOR330 2016
 Finished    445
Name: Status, dtype: int64
 ****************************************
TOR330 2014
 Finished    443
Name: Status, dtype: int64
 ****************************************
TOR330 2013
 Finished    383
Name: Status, dtype: int64
 ****************************************
TOR330 2012
 Finished    391
Name: Status, dtype: int64
 ****************************************
TOR330 2011
 Finished    300
Name: Status, dtype: int64
 ****************************************
TOR330 2010
 Finished    179
Name: Status, dtype: int64
 ****************************************
TOR450 2024
 DNF         100
Finished     68
Name: Status, dtype: int64
 ****************************************
TOR450 2023
 DNF         88
Finished    85
Name: Status, dtype: int64
 ****************************************
TOR450 2022
 Finished                    46
Finished at Hotel Italia    11
Name: Status, dtype: int64
 ****************************************
TOR450 2021
 Finished    31
DNF         25
Name: Status, dtype: int64
 ****************************************
TOR450 2019
 DNF         60
Finished    40
Name: Status, dtype: int64
 ****************************************

## EDA of ITRA

In [10]:
TORX_itra_df[TORX_itra_df['Sex'].isna()]

,Name,Age,Sex,ITRA_Nationality,Performance,Performance_Seconds,Status,Year,Race
643,Coluccio Pasquale,60,NaN,ITA,NaT,NaN,DNF,2024,TOR330
1223,Bryant Shane,45,NaN,USA,4 days 23:30:03,430203.0,Finished,2023,TOR330
1608,DAngelo Deva,33,NaN,ITA,6 days 01:56:32,525392.0,Finished,2023,TOR330
1760,Cailleau Marie Aline,56,NaN,FRA,NaT,NaN,DNF,2023,TOR330
2307,Carlier Julien,43,NaN,FRA,4 days 20:36:16,419776.0,Finished,2022,TOR330
2419,Barrot Loic,41,NaN,FRA,5 days 06:22:53,454973.0,Finished,2022,TOR330
2698,Coluccio Pasquale,58,NaN,ITA,5 days 13:42:05,481325.0,Finished at Bosses,2022,TOR330
3180,Polotti Diego,49,NaN,ITA,6 days 05:02:17,536537.0,Finished,2021,TOR330
3259,Coluccio Pasquale,57,NaN,ITA,NaT,NaN,DNF,2021,TOR330
4831,Martignoni Alessandro,40,NaN,ITA,6 days 00:29:36,520176.0,Finished,2018,TOR330
5023,Coluccio Pasquale,54,NaN,ITA,NaT,NaN,DNF,2018,TOR330
5638,Oktem Ozgur,41,NaN,TUR,6 days 01:23:58,523438.0,Finished,2017,TOR330
7018,Coluccio Pasquale,49,NaN,ITA,6 days 04:24:39,534279.0,Finished,2013,TOR330

In [11]:
TORX_itra_df[TORX_itra_df['Name'] == 'D Haene Francois']

,Name,Age,Sex,ITRA_Nationality,Performance,Performance_Seconds,Status,Year,Race
0,D Haene Francois,39,M,FRA,2 days 21:08:32,248912.0,Finished,2024,TOR330

In [12]:
TORX_itra_df[TORX_itra_df['Name'] == 'Tierney Paul']

,Name,Age,Sex,ITRA_Nationality,Performance,Performance_Seconds,Status,Year,Race
2779,Tierney Paul,39,M,IRL,3 days 16:05:51,317151.0,Finished,2021,TOR330
4441,Tierney Paul,36,M,IRL,3 days 22:39:26,340766.0,Finished,2018,TOR330
5324,Tierney Paul,35,M,IRL,4 days 03:09:44,356984.0,Finished,2017,TOR330
8064,Tierney Paul,42,M,IRL,NaT,NaN,DNF,2024,TOR450
8076,Tierney Paul,41,M,IRL,5 days 15:22:00,487320.0,Finished,2023,TOR450
8246,Tierney Paul,40,M,IRL,5 days 16:23:20,491000.0,Finished,2022,TOR450

In [13]:
TORX_itra_df[TORX_itra_df['Name'].str.contains('Girolami Paolo')]

,Name,Age,Sex,ITRA_Nationality,Performance,Performance_Seconds,Status,Year,Race
1508,Girolami Paolo,51,M,ITA,5 days 21:59:50,511190.0,Finished,2023,TOR330
2723,Girolami Paolo,50,M,ITA,5 days 15:49:42,488982.0,Finished at Bosses,2022,TOR330
3818,Girolami Paolo,47,M,ITA,5 days 19:57:42,503862.0,Finished,2019,TOR330
4824,Girolami Paolo,46,M,ITA,5 days 23:54:43,518083.0,Finished,2018,TOR330
5654,Girolami Paolo,45,M,ITA,6 days 01:52:54,525174.0,Finished,2017,TOR330

### Extracting only Finishers

In [14]:
# TORX_itra_df
TORX_itra_no_DNF = TORX_itra_df[(TORX_itra_df['Status'] != 'DNF') &
                                (TORX_itra_df['Race'] != race) 
                                 # & (TORX_itra_df['Year'] != year)
                               ].reset_index(drop = True)
TORX_itra_no_DNF = TORX_itra_no_DNF[[
    'Name', 'ITRA_Nationality', 'Sex',  'Age', 
    'Performance','Performance_Seconds','Status', 
    'Race', 'Year'
]]

In [15]:
TORX_itra_no_DNF['Status'].unique()

array(['Finished', 'Finished at Rifugio Frassati', 'Finished at Bosses'],
      dtype=object)

In [16]:
TORX_itra_no_DNF.isna().sum()

Name                   0
ITRA_Nationality       0
Sex                    9
Age                    0
Performance            0
Performance_Seconds    0
Status                 0
Race                   0
Year                   0
dtype: int64

In [17]:
TORX_itra_no_DNF.head()

,Name,ITRA_Nationality,Sex,Age,Performance,Performance_Seconds,Status,Race,Year
0,D Haene Francois,FRA,M,39,2 days 21:08:32,248912.0,Finished,TOR330,2024
1,Marmissolle Benat,FRA,M,43,3 days 01:10:18,263418.0,Finished,TOR330,2024
2,Perrier Martin,FRA,M,34,3 days 03:35:59,272159.0,Finished,TOR330,2024
3,Macchi Andrea,ITA,M,38,3 days 04:43:09,276189.0,Finished,TOR330,2024
4,Hall Damian,GBR,M,49,3 days 04:49:20,276560.0,Finished,TOR330,2024

### This data might be used later data Visualisations

In [18]:
# grabbing all finishers 
TORX_itra_no_DNF['Performance'] = TORX_itra_no_DNF['Performance'].astype('str')



for race in ['TOR130', 'TOR330', 'TOR450']:
    df = TORX_itra_no_DNF[TORX_itra_no_DNF['Race'] == race]
    print(df.head)
    # # Save the result
    df.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_itra_no_DNF.xlsx' , index = False)

<bound method NDFrame.head of Empty DataFrame
Columns: [Name, ITRA_Nationality, Sex, Age, Performance, Performance_Seconds, Status, Race, Year]
Index: []>
<bound method NDFrame.head of                      Name ITRA_Nationality Sex Age      Performance  \
0        D Haene Francois              FRA   M  39  2 days 21:08:32
1       Marmissolle Benat              FRA   M  43  3 days 01:10:18
2          Perrier Martin              FRA   M  34  3 days 03:35:59
3           Macchi Andrea              ITA   M  38  3 days 04:43:09
4             Hall Damian              GBR   M  49  3 days 04:49:20
...                   ...              ...  ..  ..              ...
5869      Marmier Natacha              FRA   F  55  6 days 04:37:16
5870  Marmier Jean Claude              FRA   M  67  6 days 04:37:20
5871         Slagel Craig              CAN   M  38  6 days 04:38:00
5872        Dawirs Michel              BEL   M  52  6 days 04:43:34
5873            Riz Luigi              ITA   M  54  6 days 05:58:03

      Performance_Seconds    Status    Race  Year
0                248912.0  Finished  TOR330  2024
1                263418.0  Finished  TOR330  2024
2                272159.0  Finished  TOR330  2024
3                276189.0  Finished  TOR330  2024
4                276560.0  Finished  TOR330  2024
...                   ...       ...     ...   ...
5869             535036.0  Finished  TOR330  2010
5870             535040.0  Finished  TOR330  2010
5871             535080.0  Finished  TOR330  2010
5872             535414.0  Finished  TOR330  2010
5873             539883.0  Finished  TOR330  2010

[5874 rows x 9 columns]>
<bound method NDFrame.head of Empty DataFrame
Columns: [Name, ITRA_Nationality, Sex, Age, Performance, Performance_Seconds, Status, Race, Year]
Index: []>